# SPDX-License-Identifier: GPL-2.0-only

DEP_DIRS += $(BASE_DEP_DIR)/core
TARGET_BIN_CC += $(BASE_DIR)/core/main.o
OBJ_CC += \
	$(BASE_DIR)/core/print.o \
	$(BASE_DIR)/core/ring.o \
	$(BASE_DIR)/core/thread.o \
	$(BASE_DIR)/core/workqueue.o

